### ISSUE TITLE
error message displayed when i execute 'cargo build --release'

### ISSUE THREAD

**Issue by lamei1224** [b00f/durian#13]
![error](https://user-images.githubusercontent.com/55862430/85132074-a7388c80-b26a-11ea-8ae2-d30f6fa1d6b7.png)

**Comment by lamei1224** [comment]
![version](https://user-images.githubusercontent.com/55862430/85132338-2201a780-b26b-11ea-9eed-fce69e9a838f.png)

**Comment by b00f** [comment]
@lamei1224 Thanks for using Durian. 

I think capnp version is too old. Your capnp version is 0.4 but the latest version is 0.8. Please upgrade your capnp tools to the latest version. Check [here](https://capnproto.org/install.html) to get the latest version of capnp

**Comment by lamei1224** [comment]
I installed it according to the document you sent, but when I ‘make’ it, I get an error. 
Error Message displays "make No targets specified and no makefile found.stop."when i 'make'it
Error Message displays "make No rule to make target 'install'.stop."when i 'make install'it
Do you know how to solve it? i cannot install the latest version.please help me

**Comment by lamei1224** [comment]
I have solved this problem,thank you.Do you know what to do next?

**Comment by b00f** [comment]
Good. Sorry for the lack of documentation. We are still on the development phase. Soon we will come with better documentation. Until then please follow the readmes.

I close this ticket.
