### ISSUE TITLE
Error message displayed when i execute 'cargo run' on durian-server

### ISSUE THREAD

**Issue by lamei1224** [b00f/durian#14]
![error1](https://user-images.githubusercontent.com/55862430/85224884-ffed5e00-b3ff-11ea-869c-878056edfc0e.png)
![error2](https://user-images.githubusercontent.com/55862430/85224885-02e84e80-b400-11ea-9791-33b011a56a29.png)

**Comment by b00f** [comment]
@lamei1224 May I reach have your email address? I am going to invite you in google meet to solve your issue

**Comment by lamei1224** [comment]
my email is 1628604440@qq.com. thank you

**Comment by b00f** [comment]
Check your rust version is the latest. And also make sure you have installed the latest capnp tools.

**Comment by lamei1224** [comment]
yes，it is the latest.
![versios](https://user-images.githubusercontent.com/55862430/85241923-03b8c900-b470-11ea-8eb7-c28db7eccbbd.png)

**Comment by lamei1224** [comment]
i want to see how it works,and i want to know do I need to install any other tools.
![here](https://user-images.githubusercontent.com/55862430/85245456-336cce80-b47a-11ea-9daa-262c4daf869f.png)

can you write more details?like this:
![statelss](https://user-images.githubusercontent.com/55862430/85245580-9eb6a080-b47a-11ea-95a6-37c5a51eb87a.png)

**Comment by b00f** [comment]
@lamei1224 Could you please get the latest code and try. I added `time` and `sync` features.

Document is not published yet. It's under review and only people who have access can check it.

**Comment by b00f** [comment]
@lamei1224 You can check [here](https://github.com/b00f/durian/blob/master/durian-server/README.md) and [here](https://github.com/b00f/durian/tree/master/examples/durian-client) to see how to use durian as a web service.

**Comment by lamei1224** [comment]
Ok，let me try.

**Comment by lamei1224** [comment]
I am sorry,Still a problem.
![error](https://user-images.githubusercontent.com/55862430/85257435-73db4500-b498-11ea-8e4a-bdd4f1aa1190.png)

**Comment by b00f** [comment]
Please check again.

**Comment by lamei1224** [comment]
It doesn’t matter, my ‘cargo run’ succeeded on durian-server.Thank you very much!

**Comment by b00f** [comment]
Good. You need to run cargo client to test the Durian. Have fun. I close this issue.
