### ISSUE TITLE
i cannot open page when i start the server and run' ./target/debug/durian localhost:8080'

### ISSUE THREAD

**Issue by lamei1224** [b00f/durian#16]
![error](https://user-images.githubusercontent.com/55862430/85357438-e48b6b80-b543-11ea-9441-481698c63f05.png)

**Comment by lamei1224** [comment]
![error](https://user-images.githubusercontent.com/55862430/85357821-c96d2b80-b544-11ea-9f5e-69e4997cb4c2.png)

**Comment by lamei1224** [comment]
![client](https://user-images.githubusercontent.com/55862430/85358474-6ed4cf00-b546-11ea-8f2e-ac34a043f8be.png)

**Comment by lamei1224** [comment]
How to display it on a web page

**Comment by lamei1224** [comment]
Am I doing the wrong steps? Can you help me？

**Comment by nagarajmanjunath** [comment]
It does not include GUI, It works based on client and web service.

**Comment by lamei1224** [comment]
@b00f if no GUI, How do I check the transaction status of my account? Is there a specific operation method?

just durian [ip address:prot] or durian-server [ip address:prot] even or durian-client [ip address:prot],Nothing is displayed, only account. So how do you go about trading?

**Comment by b00f** [comment]
That is not part of Durian. Durian is a stateless blockchain VM, it means it doesn't know and keep any information about blockchain. It just run and deploy the smart contracts.

**Comment by lamei1224** [comment]
OK，thank you
